"""initial schema

Revision ID: 8d9b5ad079b9
Revises: 
Create Date: 2026-06-06 13:58:41.680249
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8d9b5ad079b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('program', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_index(op.f('ix_app_user_role'), 'app_user', ['role'], unique=False)
    op.create_table('career',
    sa.Column('career_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('career_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('career_group', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('program', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_placeholder_name', sa.Boolean(), nullable=False),
    sa.Column('competency_vector', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('career_id')
    )
    op.create_index(op.f('ix_career_career_group'), 'career', ['career_group'], unique=False)
    op.create_index(op.f('ix_career_program'), 'career', ['program'], unique=False)
    op.create_table('competency',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label_th', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competency_domain'), 'competency', ['domain'], unique=False)
    op.create_table('course',
    sa.Column('course_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price_thb', sa.Integer(), nullable=False),
    sa.Column('duration_hours', sa.Integer(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('affiliate', sa.Boolean(), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('faculty_gap_snapshot',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('competency_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avg_gap', sa.Float(), nullable=False),
    sa.Column('students_below_threshold', sa.Integer(), nullable=False),
    sa.Column('module_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('next_term_forecast', sa.Integer(), nullable=True),
    sa.Column('trend', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculty_gap_snapshot_academic_year'), 'faculty_gap_snapshot', ['academic_year'], unique=False)
    op.create_table('assessment_result',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('anon_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('program', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('input_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dream_career_group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dream_career_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('top10', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_result_anon_id'), 'assessment_result', ['anon_id'], unique=False)
    op.create_index(op.f('ix_assessment_result_user_id'), 'assessment_result', ['user_id'], unique=False)
    op.create_table('company_demand',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('career_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('openings', sa.Integer(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['career.career_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_demand_career_id'), 'company_demand', ['career_id'], unique=False)
    op.create_index(op.f('ix_company_demand_snapshot_date'), 'company_demand', ['snapshot_date'], unique=False)
    op.create_table('competency_course',
    sa.Column('competency_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('course_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competency.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.PrimaryKeyConstraint('competency_id', 'course_id')
    )
    op.create_table('lead_candidate',
    sa.Column('lead_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mes_score', sa.Float(), nullable=False),
    sa.Column('target_track', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transcript_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transcript_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('caria_report_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('caria_report_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('lead_id')
    )
    op.create_index(op.f('ix_lead_candidate_user_id'), 'lead_candidate', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_candidate_user_id'), table_name='lead_candidate')
    op.drop_table('lead_candidate')
    op.drop_table('competency_course')
    op.drop_index(op.f('ix_company_demand_snapshot_date'), table_name='company_demand')
    op.drop_index(op.f('ix_company_demand_career_id'), table_name='company_demand')
    op.drop_table('company_demand')
    op.drop_index(op.f('ix_assessment_result_user_id'), table_name='assessment_result')
    op.drop_index(op.f('ix_assessment_result_anon_id'), table_name='assessment_result')
    op.drop_table('assessment_result')
    op.drop_index(op.f('ix_faculty_gap_snapshot_academic_year'), table_name='faculty_gap_snapshot')
    op.drop_table('faculty_gap_snapshot')
    op.drop_table('course')
    op.drop_index(op.f('ix_competency_domain'), table_name='competency')
    op.drop_table('competency')
    op.drop_index(op.f('ix_career_program'), table_name='career')
    op.drop_index(op.f('ix_career_career_group'), table_name='career')
    op.drop_table('career')
    op.drop_index(op.f('ix_app_user_role'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
