export interface CareerItem {
  name: string;
  nameTh?: string;
  description: string;
  descriptionEn?: string;
  /** 2-3 representative skills/tools, shown as tags in the sub-career hover popover. */
  skills?: string[];
}

export interface CareerGroup {
  name: string;
  nameTh?: string;
  careers: CareerItem[];
}

export const DT_BRANCH: CareerGroup[] = [
  {
    name: "Web Application Professionals",
    nameTh: "กลุ่มที่ 1: นักพัฒนาเว็บแอปพลิเคชัน",
    careers: [
      { name: "Web Designer", nameTh: "ผู้ออกแบบเว็บไซต์", description: "ออกแบบหน้าตาและส่วนติดต่อผู้ใช้ (UI) ของเว็บไซต์ให้สวยงาม ใช้งานง่าย และสอดคล้องกับตัวตนของแบรนด์ ตั้งแต่การวางเลย์เอาต์ การเลือกใช้สีและตัวอักษร ไปจนถึงการจัดวางภาพและปุ่มต่าง ๆ บทบาทนี้คือด่านแรกที่สร้างความประทับใจให้ผู้เข้าชม และทำงานใกล้ชิดกับนักพัฒนาเพื่อให้ดีไซน์ที่วางไว้ใช้งานได้จริงและแสดงผลสวยงามบนทุกขนาดหน้าจอ", descriptionEn: "Designs the visual interface and layout of websites, choosing colors, typography, and imagery that reflect the brand and guide visitors with ease. Works closely with developers so every design translates faithfully into a responsive, polished experience across all screen sizes.", skills: ["Figma", "HTML/CSS", "UI Design"] },
      { name: "Web Developer", nameTh: "นักพัฒนาเว็บ", description: "เขียนโค้ดเพื่อสร้างและควบคุมการทำงานของเว็บไซต์ ทั้งส่วนหน้าบ้าน (Frontend) ที่ผู้ใช้มองเห็นและโต้ตอบ และส่วนหลังบ้าน (Backend) ที่ประมวลผลและจัดเก็บข้อมูล เชื่อมต่อฐานข้อมูลและ API เพื่อให้ระบบทำงานได้ครบถ้วน รวดเร็ว และปลอดภัย เป็นกำลังหลักที่เปลี่ยนดีไซน์และไอเดียให้กลายเป็นเว็บที่ใช้งานได้จริง", descriptionEn: "Writes the code that powers websites end to end, from the frontend interface users interact with to the backend logic that processes and stores data. Connects databases and APIs to keep the system fast, reliable, and secure, turning designs and ideas into a working product.", skills: ["JavaScript", "React", "Node.js"] },
      { name: ".NET Programmer", nameTh: "นักโปรแกรมระบบ .NET", description: "พัฒนาโปรแกรมและแอปพลิเคชันสำหรับองค์กรขนาดใหญ่ด้วยเทคโนโลยีในสแต็ก .NET และภาษา C# เน้นการสร้างระบบที่รองรับผู้ใช้จำนวนมาก มีความเสถียร ปลอดภัย และดูแลรักษาง่ายตามมาตรฐานองค์กร บทบาทนี้สำคัญต่อธุรกิจที่ต้องการระบบหลังบ้านที่เชื่อถือได้และเชื่อมต่อกับโครงสร้างเดิมขององค์กรได้อย่างราบรื่น", descriptionEn: "Builds enterprise-grade programs and applications using the Microsoft .NET stack and the C# language. Focuses on systems that stay stable, secure, and maintainable at scale, integrating smoothly with an organization's existing infrastructure.", skills: ["C#", ".NET", "SQL Server"] },
      { name: "Web Master", nameTh: "ผู้ดูแลเว็บไซต์", description: "ดูแลภาพรวมของเว็บไซต์ให้พร้อมใช้งานและเปิดได้ตลอดเวลา ครอบคลุมการตั้งค่าเซิร์ฟเวอร์ ความปลอดภัย การสำรองข้อมูล และการต่ออายุโดเมน คอยตรวจสอบประสิทธิภาพ แก้ไขปัญหาเฉพาะหน้า และวางแผนป้องกันไม่ให้เว็บล่ม จึงเป็นผู้รักษาความน่าเชื่อถือและความต่อเนื่องของบริการออนไลน์ขององค์กร", descriptionEn: "Keeps a website healthy and online around the clock, handling server configuration, security, backups, and domain upkeep. Monitors performance and resolves issues before they cause downtime, safeguarding the reliability of the organization's online presence.", skills: ["Linux", "DNS", "Security"] },
      { name: "UI/UX Designer", nameTh: "ผู้ออกแบบประสบการณ์ผู้ใช้", description: "วิเคราะห์พฤติกรรมและความต้องการของผู้ใช้จริง แล้วออกแบบขั้นตอนการใช้งานให้เข้าใจง่าย ลื่นไหล และน่าพึงพอใจ สร้างต้นแบบ (Prototype) และทดสอบกับผู้ใช้เพื่อค้นหาจุดติดขัดและปรับปรุงก่อนส่งให้ทีมพัฒนา บทบาทนี้ช่วยลดความสับสนของผู้ใช้และเพิ่มโอกาสที่ผลิตภัณฑ์จะประสบความสำเร็จในตลาด", descriptionEn: "Studies real user behavior and needs, then designs flows that feel intuitive, smooth, and satisfying to use. Builds prototypes and runs usability tests to find friction early, reducing confusion and raising the product's chance of success in the market.", skills: ["Figma", "User Research", "Prototyping"] }
    ]
  },
  {
    name: "Mobile Application Professionals",
    nameTh: "กลุ่มที่ 2: นักพัฒนาแอปพลิเคชันมือถือ",
    careers: [
      { name: "Cross-platform Mobile Developer", nameTh: "นักพัฒนาแอปหลายแพลตฟอร์ม", description: "สร้างแอปบนมือถือที่ทำงานได้ทั้งระบบ iOS และ Android จากโค้ดชุดเดียว ช่วยให้พัฒนาได้เร็วขึ้นและดูแลรักษาง่ายในระยะยาว ใช้เฟรมเวิร์กอย่าง Flutter หรือ React Native เพื่อให้แอปทำงานลื่นไหลใกล้เคียงแอปเนทีฟ บทบาทนี้ช่วยธุรกิจประหยัดต้นทุนและเข้าถึงผู้ใช้ทั้งสองระบบได้พร้อมกัน", descriptionEn: "Builds mobile apps that run on both iOS and Android from a single codebase, speeding up development and easing long-term maintenance. Uses frameworks like Flutter or React Native to deliver near-native performance while helping businesses reach both platforms at once.", skills: ["Flutter", "React Native", "Dart"] },
      { name: "Xamarin Mobile Developer", nameTh: "นักพัฒนาแอป Xamarin", description: "ใช้เครื่องมือ Xamarin ร่วมกับภาษา C# สร้างแอปมือถือระดับองค์กรที่แชร์โค้ดข้ามแพลตฟอร์มได้ เหมาะอย่างยิ่งกับองค์กรที่ใช้ระบบ .NET อยู่แล้วและต้องการให้แอปเชื่อมต่อกับระบบหลังบ้านเดิมอย่างไร้รอยต่อ บทบาทนี้ช่วยต่อยอดทรัพยากรและทักษะที่องค์กรมีอยู่ให้คุ้มค่าที่สุด", descriptionEn: "Uses Xamarin with C# to build enterprise mobile apps that share code across platforms. A strong fit for organizations already invested in .NET, letting apps connect seamlessly to existing backend systems and reuse in-house skills.", skills: ["C#", "Xamarin", ".NET"] },
      { name: "Android Mobile Developer", nameTh: "นักพัฒนาแอป Android", description: "พัฒนาแอปสำหรับระบบปฏิบัติการ Android โดยเฉพาะ ด้วยภาษา Kotlin หรือ Java ดูแลตั้งแต่การออกแบบหน้าจอ การจัดการข้อมูล ไปจนถึงการปรับแต่งประสิทธิภาพให้รองรับอุปกรณ์ Android ที่มีความหลากหลายทั้งรุ่นและขนาดหน้าจอ บทบาทนี้สำคัญต่อการเข้าถึงผู้ใช้กลุ่มใหญ่ที่สุดในตลาดมือถือทั่วโลก", descriptionEn: "Specializes in building apps for Android using Kotlin or Java, covering screen design, data handling, and performance tuning across a wide range of devices and screen sizes. Key to reaching the largest user base in the global mobile market.", skills: ["Kotlin", "Java", "Android SDK"] },
      { name: "iOS Mobile Developer", nameTh: "นักพัฒนาแอป iOS", description: "พัฒนาแอปสำหรับ iPhone และ iPad ด้วยภาษา Swift โดยยึดแนวทางการออกแบบของ Apple เพื่อมอบประสบการณ์ใช้งานที่ลื่นไหลและประณีต ดูแลครบวงจรตั้งแต่การเขียนโค้ด การทดสอบ ไปจนถึงการนำแอปขึ้น App Store บทบาทนี้เหมาะกับผู้ที่ใส่ใจรายละเอียดและคุณภาพของประสบการณ์ผู้ใช้ระดับพรีเมียม", descriptionEn: "Builds apps for iPhone and iPad with Swift, following Apple's design guidelines to deliver a refined, fluid experience. Owns the full cycle from coding and testing to App Store release, ideal for those who care about premium, detail-driven user experience.", skills: ["Swift", "SwiftUI", "Xcode"] },
      { name: "Mobile Application Developer", nameTh: "นักพัฒนาโมบายล์แอปพลิเคชัน", description: "ออกแบบ พัฒนา และทดสอบแอปพลิเคชันบนมือถือและอุปกรณ์พกพาหลากหลายประเภท ดูแลทั้งฟังก์ชันการทำงานและการเชื่อมต่อข้อมูลกับเซิร์ฟเวอร์ เพื่อให้แอปตอบโจทย์ผู้ใช้และทำงานได้อย่างเสถียร เป็นบทบาทที่ครอบคลุมตั้งแต่แนวคิดเริ่มต้นจนถึงการดูแลแอปหลังเปิดให้บริการจริง", descriptionEn: "Designs, develops, and tests applications across a range of smartphones and handheld devices, handling both functionality and server connectivity. Covers the journey from initial concept to post-launch support, keeping apps stable and aligned with user needs.", skills: ["Mobile UI", "REST API", "Testing"] }
    ]
  },
  {
    name: "Enterprise Software Professionals",
    nameTh: "กลุ่มที่ 3: นักพัฒนาซอฟต์แวร์ระดับองค์กร",
    careers: [
      { name: "Software Developer", nameTh: "นักพัฒนาซอฟต์แวร์", description: "พัฒนา เขียน และปรับปรุงโปรแกรมให้ตอบโจทย์ความต้องการทางธุรกิจ ตั้งแต่รับโจทย์ ออกแบบแนวทางแก้ปัญหา ไปจนถึงการเขียนโค้ดและแก้ไขข้อผิดพลาด (Bugs) เป็นหัวใจสำคัญที่เปลี่ยนความต้องการขององค์กรให้กลายเป็นซอฟต์แวร์ที่ใช้งานได้จริง และทำงานร่วมกับทีมอย่างต่อเนื่องเพื่อส่งมอบฟีเจอร์ใหม่และยกระดับคุณภาพของระบบให้ดีขึ้นเรื่อย ๆ", descriptionEn: "Develops, writes, and refines programs that solve real business problems, from understanding requirements and designing a solution to coding it and fixing bugs. Acts as the engine that turns an organization's needs into working software, collaborating with the team to ship new features and steadily improve quality.", skills: ["Python", "Git", "SQL"] },
      { name: "System Analyst", nameTh: "นักวิเคราะห์ระบบ", description: "ทำหน้าที่เป็นสะพานเชื่อมระหว่างทีมธุรกิจและทีมพัฒนา โดยเก็บรวบรวมความต้องการแล้วแปลงให้เป็นข้อกำหนดและแผนผังระบบที่ชัดเจน ออกแบบโครงสร้างระบบและฐานข้อมูลเพื่อให้ทีมพัฒนานำไปสร้างได้ตรงเป้าหมาย บทบาทนี้ช่วยลดความเข้าใจผิดและความสูญเปล่าในโครงการ ทำให้ซอฟต์แวร์ที่ออกมาตรงกับสิ่งที่ธุรกิจต้องการจริง ๆ", descriptionEn: "Bridges the business and development teams by gathering requirements and translating them into clear specifications and system diagrams. Designs the system structure and database so developers build the right thing, cutting miscommunication and waste so the final software truly matches business needs.", skills: ["UML", "Requirements", "SQL"] },
      { name: "Software Engineer", nameTh: "วิศวกรซอฟต์แวร์", description: "ประยุกต์หลักการทางวิศวกรรมในการออกแบบและสร้างระบบซอฟต์แวร์ขนาดใหญ่ที่เชื่อถือได้และขยายตัวได้ ดูแลตั้งแต่สถาปัตยกรรมของระบบ การเขียนโค้ดคุณภาพสูง ไปจนถึงการทดสอบและการดูแลรักษาหลังใช้งานจริง บทบาทนี้เน้นความยั่งยืนและประสิทธิภาพของระบบในระยะยาว ไม่ใช่แค่การทำให้โปรแกรมทำงานได้เท่านั้น", descriptionEn: "Applies engineering principles to design and build large, reliable, and scalable software systems. Owns everything from architecture and high-quality code to testing and long-term maintenance, focusing on sustainability and performance rather than just making the program run.", skills: ["Java", "System Design", "CI/CD"] },
      { name: "Software Tester", nameTh: "นักทดสอบซอฟต์แวร์", description: "ตรวจสอบและค้นหาข้อผิดพลาด (Bugs) ของโปรแกรมก่อนส่งถึงมือผู้ใช้จริง ออกแบบกรณีทดสอบทั้งแบบทำมือและแบบอัตโนมัติเพื่อยืนยันว่าทุกฟังก์ชันทำงานถูกต้อง บทบาทนี้เป็นด่านสุดท้ายที่ปกป้องคุณภาพและชื่อเสียงของผลิตภัณฑ์ ช่วยลดความเสี่ยงและต้นทุนจากความผิดพลาดที่อาจเกิดขึ้นหลังเปิดใช้งาน", descriptionEn: "Verifies functionality and hunts for bugs before software reaches users, designing both manual and automated test cases to confirm everything works as intended. Serves as the last line of defense for product quality, reducing the risk and cost of failures after release.", skills: ["QA", "Selenium", "Test Cases"] },
      { name: "Embedded System Programmer", nameTh: "นักเขียนโปรแกรมระบบฝังตัว", description: "เขียนโค้ดระดับล่างเพื่อควบคุมไมโครคอนโทรลเลอร์ วงจรอิเล็กทรอนิกส์ และอุปกรณ์ IoT ทำงานใกล้ชิดกับฮาร์ดแวร์เพื่อให้ระบบขนาดเล็กทำงานได้อย่างแม่นยำ เสถียร และประหยัดพลังงาน บทบาทนี้เป็นหัวใจเบื้องหลังอุปกรณ์อัจฉริยะรอบตัวเรา ตั้งแต่เครื่องใช้ไฟฟ้าไปจนถึงระบบในยานยนต์และโรงงาน", descriptionEn: "Writes low-level code to control microcontrollers, electronic circuits, and IoT devices, working close to the hardware so small systems run precisely, reliably, and efficiently. Powers the smart devices around us, from home appliances to automotive and factory systems.", skills: ["C/C++", "IoT", "Microcontrollers"] }
    ]
  },
  {
    name: "Data Handling Professionals",
    nameTh: "กลุ่มที่ 4: ผู้จัดการคลังและคัดกรองข้อมูลดิจิทัล",
    careers: [
      { name: "Data Archivists", nameTh: "นักจัดเก็บเอกสารและข้อมูลสำคัญ", description: "จัดเก็บ รวบรวม และปกป้องเอกสารและข้อมูลดิจิทัลสำคัญให้คงสภาพและเข้าถึงได้ในระยะยาว วางระบบจัดหมวดหมู่ การกำหนดเมทาดาทา และการสำรองข้อมูลเพื่อให้ค้นหาและนำกลับมาใช้ได้เมื่อจำเป็น บทบาทนี้สำคัญต่อองค์กรที่ต้องเก็บหลักฐาน ข้อมูลทางกฎหมาย หรือความทรงจำขององค์กรไว้อย่างปลอดภัย", descriptionEn: "Organizes, collects, and protects important digital records so they stay intact and accessible for the long term. Sets up classification, metadata, and backup systems so information can be found and reused when needed, crucial for legal evidence and institutional memory.", skills: ["Metadata", "Archiving", "Storage"] },
      { name: "Digital Librarians", nameTh: "บรรณารักษ์ดิจิทัล", description: "บริหารคลังความรู้และระบบสืบค้นข้อมูลอิเล็กทรอนิกส์ขององค์กร จัดระเบียบและทำดัชนีทรัพยากรดิจิทัลให้เป็นระบบ เพื่อช่วยให้ผู้ใช้เข้าถึงข้อมูลที่ต้องการได้อย่างรวดเร็วและถูกต้อง บทบาทนี้ผสานทักษะด้านสารสนเทศเข้ากับเทคโนโลยี เพื่อทำให้ความรู้จำนวนมหาศาลกลายเป็นสิ่งที่ค้นหาและใช้งานได้ง่าย", descriptionEn: "Manages digital repositories and electronic search systems, organizing and indexing resources so users can find accurate information fast. Blends information science with technology to make vast collections of knowledge easy to search and use.", skills: ["Cataloging", "Search", "Metadata"] },
      { name: "Digital Data Curator", nameTh: "ผู้คัดสรรข้อมูลดิจิทัล", description: "จัดหมวดหมู่ ทำดัชนี และทำความสะอาดชุดข้อมูลให้มีคุณภาพและพร้อมใช้งาน ดูแลรูปแบบและมาตรฐานของข้อมูลเพื่อให้ทีมวิเคราะห์หยิบไปใช้ต่อได้ทันทีโดยไม่ต้องเสียเวลาแก้ไขซ้ำ บทบาทนี้คือผู้รักษาคุณภาพต้นทางของข้อมูล ซึ่งเป็นรากฐานสำคัญของการวิเคราะห์และการตัดสินใจที่แม่นยำ", descriptionEn: "Categorizes, indexes, and cleans datasets so they are high quality and ready to use, maintaining consistent formats and standards. Protects data quality at the source, the foundation that lets analytics teams work immediately and make accurate decisions.", skills: ["Data Cleaning", "Excel", "SQL"] },
      { name: "Data Stewards", nameTh: "ผู้ดูแลสิทธิ์และคุณภาพข้อมูล", description: "กำหนดและดูแลนโยบายการใช้งานข้อมูล ความถูกต้อง และสิทธิ์การเข้าถึงให้เป็นไปตามมาตรฐานและกฎหมาย เช่น PDPA คอยตรวจสอบให้การจัดการข้อมูลขององค์กรโปร่งใส ปลอดภัย และตรวจสอบย้อนกลับได้ บทบาทนี้สำคัญมากขึ้นเรื่อย ๆ ในยุคที่ข้อมูลส่วนบุคคลและความเป็นส่วนตัวกลายเป็นเรื่องที่ทุกองค์กรต้องรับผิดชอบ", descriptionEn: "Defines and enforces policies for data usage, accuracy, and access rights in line with standards and laws such as PDPA. Keeps data governance transparent, secure, and auditable, a role that grows more important as privacy and personal data become every organization's responsibility.", skills: ["Data Governance", "PDPA", "Quality"] }
    ]
  },
  {
    name: "Data Science Professionals",
    nameTh: "กลุ่มที่ 5: วิทยาการข้อมูลและการวิเคราะห์",
    careers: [
      { name: "Data Architect", nameTh: "สถาปนิกข้อมูล", description: "ออกแบบโครงสร้างและเส้นทางการไหลของข้อมูลทั้งหมดในองค์กร วางมาตรฐานการจัดเก็บ การเชื่อมต่อระบบ และความปลอดภัยของข้อมูล เพื่อให้ข้อมูลพร้อมใช้ น่าเชื่อถือ และขยายตัวรองรับการเติบโตในอนาคต บทบาทนี้เปรียบเสมือนผู้วางพิมพ์เขียวที่กำหนดว่าข้อมูลขององค์กรจะถูกจัดการอย่างเป็นระบบเพียงใด", descriptionEn: "Designs the overall structure and flow of data across the organization, setting standards for storage, integration, and security. Acts as the blueprint-maker who ensures data stays available, trustworthy, and ready to scale with future growth.", skills: ["Data Modeling", "SQL", "Cloud"] },
      { name: "Data Engineer", nameTh: "วิศวกรข้อมูล", description: "สร้างท่อส่งข้อมูล (Data Pipelines) และคลังข้อมูลเพื่อรวบรวม แปลง และลำเลียงข้อมูลดิบให้พร้อมสำหรับการวิเคราะห์ ดูแลให้ข้อมูลไหลเข้าระบบอย่างถูกต้อง ครบถ้วน และตรงเวลา บทบาทนี้เป็นเบื้องหลังสำคัญที่ทำให้นักวิทยาศาสตร์ข้อมูลและนักวิเคราะห์มีข้อมูลคุณภาพดีไว้ทำงาน", descriptionEn: "Builds data pipelines and warehouses that collect, transform, and move raw data into a form ready for analysis. Ensures data flows in accurately, completely, and on time, the backbone that gives data scientists and analysts clean, reliable data to work with.", skills: ["Python", "SQL", "Spark"] },
      { name: "Data Scientist", nameTh: "นักวิทยาศาสตร์ข้อมูล", description: "ใช้สถิติ คณิตศาสตร์ และโมเดล AI/ML วิเคราะห์ข้อมูลเพื่อค้นหาอินไซต์เชิงลึกและพยากรณ์แนวโน้มในอนาคต สร้าง ฝึก และทดสอบโมเดลเพื่อช่วยให้องค์กรตัดสินใจบนพื้นฐานของข้อมูลจริง บทบาทนี้เปลี่ยนข้อมูลจำนวนมหาศาลให้กลายเป็นคำตอบและโอกาสทางธุรกิจที่จับต้องได้", descriptionEn: "Uses statistics, mathematics, and AI/ML models to dig deep insights out of data and forecast future trends. Builds, trains, and tests models that help organizations decide based on real evidence, turning vast data into tangible answers and business opportunities.", skills: ["Python", "Machine Learning", "Statistics"] },
      { name: "Data Analyst", nameTh: "นักวิเคราะห์ข้อมูล", description: "รวบรวมและประมวลผลข้อมูล แล้วจัดทำแดชบอร์ดและรายงานสรุปที่เข้าใจง่ายและเห็นภาพชัดเจน ช่วยให้ทีมธุรกิจมองเห็นภาพรวมและตัดสินใจได้เร็วขึ้นจากตัวเลขจริง บทบาทนี้เป็นผู้แปลภาษาข้อมูลให้กลายเป็นเรื่องราวที่ผู้บริหารและทีมงานนำไปใช้ได้ทันที", descriptionEn: "Gathers and processes data, then builds clear dashboards and reports that make the numbers easy to grasp. Helps business teams see the big picture and decide faster, acting as the translator who turns raw data into stories people can act on.", skills: ["SQL", "Power BI", "Excel"] }
    ]
  },
  {
    name: "Cloud Technology Professionals",
    nameTh: "กลุ่มที่ 6: เทคโนโลยีคลาวด์และความปลอดภัยไซเบอร์",
    careers: [
      { name: "Network Administrator", nameTh: "ผู้ดูแลระบบเครือข่าย", description: "ติดตั้ง ดูแล และแก้ไขปัญหาระบบเครือข่ายขององค์กร ทั้งระบบสายแลน ไวไฟ และเซิร์ฟเวอร์ คอยตรวจสอบให้การเชื่อมต่อมีความเสถียร รวดเร็ว และปลอดภัยอยู่เสมอ บทบาทนี้เป็นรากฐานที่ทำให้ทุกฝ่ายในองค์กรทำงานออนไลน์และสื่อสารกันได้อย่างต่อเนื่องไม่สะดุด", descriptionEn: "Installs, maintains, and troubleshoots an organization's networks, including LAN, Wi-Fi, and servers. Keeps connections stable, fast, and secure, the foundation that lets every team stay online and communicate without interruption.", skills: ["Networking", "Linux", "Firewall"] },
      { name: "Network Analyst", nameTh: "นักวิเคราะห์ระบบเครือข่าย", description: "วิเคราะห์ประสิทธิภาพและความเสถียรของเครือข่าย ค้นหาจุดคอขวด และวางแผนขยายความจุให้รองรับการใช้งานที่เพิ่มขึ้น ออกแบบโครงสร้างเครือข่ายให้เหมาะสมกับความต้องการและงบประมาณขององค์กร บทบาทนี้ช่วยให้ระบบเครือข่ายเติบโตอย่างมีทิศทางและพร้อมรับความต้องการในอนาคต", descriptionEn: "Analyzes network performance and stability, pinpoints bottlenecks, and plans capacity to handle growing demand. Designs network structures that fit the organization's needs and budget, ensuring the network scales in a deliberate, future-ready way.", skills: ["TCP/IP", "Monitoring", "Cisco"] },
      { name: "Security Specialist", nameTh: "ผู้เชี่ยวชาญด้านความปลอดภัย", description: "ออกแบบและวางระบบป้องกันความปลอดภัยให้กับคอมพิวเตอร์และเครือข่ายขององค์กร กำหนดมาตรการป้องกันการบุกรุก และวางแนวทางรับมือเมื่อเกิดเหตุเพื่อจำกัดความเสียหาย บทบาทนี้เป็นแนวป้องกันด่านหน้าที่ปกป้องข้อมูลและทรัพย์สินดิจิทัลขององค์กรจากภัยคุกคามทางไซเบอร์ที่ซับซ้อนขึ้นทุกวัน", descriptionEn: "Designs and deploys security systems that protect an organization's computers and networks, setting intrusion defenses and incident-response plans to limit damage. Stands as the front line guarding digital assets against increasingly sophisticated cyber threats.", skills: ["Cybersecurity", "Firewall", "Encryption"] },
      { name: "Penetration Tester", nameTh: "นักทดสอบเจาะระบบ", description: "จำลองการโจมตีระบบเพื่อค้นหาช่องโหว่ก่อนที่แฮกเกอร์ตัวจริงจะเจอ ทดสอบทั้งเว็บ แอปพลิเคชัน และเครือข่ายอย่างเป็นระบบ แล้วจัดทำรายงานพร้อมคำแนะนำในการอุดช่องโหว่ให้ปลอดภัยยิ่งขึ้น บทบาทนี้คือการคิดแบบผู้โจมตีเพื่อปกป้ององค์กร และเป็นอาชีพที่เป็นที่ต้องการสูงในยุคที่ภัยไซเบอร์รุนแรงขึ้น", descriptionEn: "Simulates attacks to find vulnerabilities before real hackers do, systematically testing websites, apps, and networks and reporting fixes to harden them. Thinks like an attacker to protect the organization, a role in high demand as cyber threats intensify.", skills: ["Ethical Hacking", "Kali Linux", "OWASP"] },
      { name: "Security Analyst", nameTh: "นักวิเคราะห์ความปลอดภัยข้อมูล", description: "เฝ้าระวังการจราจรบนเครือข่ายแบบเรียลไทม์ ตรวจจับสัญญาณการโจมตี และประสานงานตอบสนองอย่างรวดเร็วเมื่อเกิดภัยคุกคาม วิเคราะห์เหตุการณ์ที่เกิดขึ้นเพื่อหาสาเหตุและป้องกันไม่ให้เกิดซ้ำในอนาคต บทบาทนี้เป็นเสมือนหน่วยเฝ้าระวังที่ทำงานตลอดเวลาเพื่อให้ระบบขององค์กรปลอดภัยอยู่เสมอ", descriptionEn: "Monitors network traffic in real time, detects signs of attack, and coordinates rapid response when threats appear. Investigates incidents to find root causes and prevent repeats, acting as the always-on watch that keeps the organization's systems safe.", skills: ["SIEM", "Incident Response", "Threat Intel"] }
    ]
  },
  {
    name: "Other Professionals",
    nameTh: "กลุ่มพิเศษ: ผู้ประกอบการและอาชีพออกแบบเฉพาะตัว",
    careers: [
      { name: "Digital Entrepreneur", nameTh: "ผู้ประกอบการดิจิทัล", description: "ริเริ่มและสร้างธุรกิจของตนเองโดยใช้เทคโนโลยีและแพลตฟอร์มดิจิทัลเป็นแกนหลัก ตั้งแต่การค้นหาไอเดีย พัฒนาผลิตภัณฑ์ ไปจนถึงการหาลูกค้าและขยายธุรกิจให้เติบโต บทบาทนี้ต้องผสมผสานทักษะด้านเทคโนโลยี การตลาด และการบริหาร เหมาะกับผู้ที่มีความคิดสร้างสรรค์และกล้าลงมือเปลี่ยนไอเดียให้กลายเป็นธุรกิจจริง", descriptionEn: "Starts and grows their own business with technology and digital platforms at its core, from finding an idea and building a product to acquiring customers and scaling up. Combines tech, marketing, and management skills, ideal for creative people ready to turn ideas into real ventures.", skills: ["Startup", "Product", "Marketing"] },
      { name: "Personalized Career", nameTh: "อาชีพออกแบบเฉพาะตัวตามสมรรถนะ", description: "เส้นทางอาชีพที่ออกแบบขึ้นเองโดยผสมผสานสมรรถนะเฉพาะตัวเข้ากับเป้าหมายและความสนใจส่วนบุคคล เหมาะกับผู้ที่ต้องการสร้างบทบาทใหม่ซึ่งยังไม่มีนิยามตายตัวในตลาดงานปัจจุบัน บทบาทนี้เปิดโอกาสให้คุณนิยามคุณค่าของตัวเองและเติบโตในทิศทางที่ตรงกับจุดแข็งที่แท้จริง", descriptionEn: "A self-designed career path that blends your unique competencies with personal goals and interests. Suited to those who want to create a role that doesn't yet have a fixed definition, letting you define your own value and grow toward your real strengths.", skills: ["Adaptability", "Self-learning", "Strategy"] }
    ]
  }
];

export const DC_BRANCH: CareerGroup[] = [
  {
    name: "Visual Design Communication Professionals",
    nameTh: "กลุ่มที่ 1: การสื่อสารการออกแบบทัศนศิลป์",
    careers: [
      { name: "Graphic Designer", nameTh: "นักออกแบบกราฟิก", description: "สร้างสรรค์งานภาพ โลโก้ และสื่อสิ่งพิมพ์ดิจิทัลเพื่อสื่อสารข้อความของแบรนด์ให้ชัดเจนและน่าจดจำ ทำงานกับสี ตัวอักษร และองค์ประกอบภาพอย่างพิถีพิถันเพื่อให้ผลงานตรงโจทย์และดึงดูดสายตา บทบาทนี้เป็นผู้สร้างภาพลักษณ์แรกที่ผู้คนสัมผัสได้จากแบรนด์ จึงมีผลโดยตรงต่อการรับรู้และความน่าเชื่อถือ", descriptionEn: "Creates visuals, logos, and digital print pieces that communicate a brand's message clearly and memorably. Works carefully with color, type, and composition to make work that is on-brief and eye-catching, shaping the first impression people form of a brand.", skills: ["Photoshop", "Illustrator", "Branding"] },
      { name: "Motion Graphic Designer", nameTh: "นักออกแบบกราฟิกเคลื่อนไหว", description: "สร้างภาพเคลื่อนไหว เอฟเฟกต์ และวิดีโอสั้นสำหรับงานโฆษณาและโซเชียลมีเดีย เปลี่ยนไอเดียและข้อความให้กลายเป็นภาพเคลื่อนไหวที่เล่าเรื่องและดึงความสนใจได้ภายในไม่กี่วินาที บทบาทนี้ตอบโจทย์ยุคที่คอนเทนต์วิดีโอครองความสนใจ และช่วยให้แบรนด์โดดเด่นท่ามกลางข้อมูลที่ท่วมท้น", descriptionEn: "Produces animations, effects, and short videos for ads and social media, turning ideas and messages into motion that tells a story and grabs attention within seconds. Answers the video-first era, helping brands stand out amid an overwhelming flow of content.", skills: ["After Effects", "Animation", "Premiere"] },
      { name: "UX/UI Designer", nameTh: "ผู้ออกแบบอินเตอร์เฟซและประสบการณ์", description: "วางโครงร่างและออกแบบหน้าตาของแอปและเว็บให้สวยงามควบคู่ไปกับการใช้งานที่ลื่นไหล วิเคราะห์เส้นทางของผู้ใช้และสร้างต้นแบบเพื่อทดสอบก่อนพัฒนาเป็นของจริง บทบาทนี้ผสานความเข้าใจในมนุษย์เข้ากับการออกแบบ เพื่อให้ผลิตภัณฑ์ดิจิทัลทั้งดูดีและใช้งานง่ายไปพร้อมกัน", descriptionEn: "Plans and designs app and web interfaces that look great and feel smooth to use, mapping user journeys and prototyping before anything is built. Merges human understanding with design so digital products are both beautiful and easy to use.", skills: ["Figma", "Prototyping", "User Flow"] },
      { name: "Web Designer", nameTh: "นักออกแบบหน้าเว็บ", description: "ออกแบบธีม อาร์ตเวิร์ก และเลย์เอาต์ของหน้าเว็บให้สอดคล้องกับแบรนด์และดึงดูดผู้เข้าชม จัดวางภาพและข้อความให้อ่านง่าย สวยงาม และแสดงผลได้ดีบนทุกขนาดหน้าจอ บทบาทนี้คือผู้สร้างความประทับใจแรกของเว็บไซต์ ซึ่งมีผลต่อการตัดสินใจอยู่ต่อหรือออกไปของผู้เข้าชมในไม่กี่วินาที", descriptionEn: "Designs themes, artwork, and page layouts that match the brand and draw visitors in, arranging imagery and text to be readable and attractive on any screen. Crafts a website's first impression, which decides in seconds whether visitors stay or leave.", skills: ["Figma", "HTML/CSS", "Visual Design"] }
    ]
  },
  {
    name: "Digital Content Creator Professionals",
    nameTh: "กลุ่มที่ 2: ผู้สร้างสรรค์เนื้อหาดิจิทัล",
    careers: [
      { name: "Digital Photographer", nameTh: "ช่างภาพดิจิทัล", description: "ถ่ายภาพและตกแต่งภาพด้วยโปรแกรมกราฟิกให้ตรงกับโจทย์ของลูกค้าและเหมาะกับการใช้งานบนสื่อดิจิทัล จัดองค์ประกอบ แสง และมุมกล้องอย่างตั้งใจเพื่อให้ได้ภาพที่เล่าเรื่องและใช้งานได้จริง บทบาทนี้เปลี่ยนช่วงเวลาและสินค้าให้กลายเป็นภาพที่สื่อสารคุณค่าและสร้างอารมณ์ร่วมกับผู้ชม", descriptionEn: "Captures and retouches photographs with graphics software to fit client briefs and digital use, composing light, framing, and angle with intent to make images that tell a story. Turns moments and products into visuals that communicate value and stir emotion.", skills: ["Photography", "Lightroom", "Photoshop"] },
      { name: "Digital Copy Writer / Blogger", nameTh: "นักเขียนคอนเทนต์และบล็อกเกอร์", description: "เขียนเนื้อหา คำโฆษณา และบทความที่มีเอกลักษณ์เพื่อเผยแพร่บนเว็บบล็อกและโซเชียลมีเดีย ปรับโทนเสียงและการใช้คำให้เหมาะกับกลุ่มเป้าหมายและช่วยให้แบรนด์สื่อสารได้ตรงใจ บทบาทนี้ใช้พลังของถ้อยคำในการสร้างความสัมพันธ์ ความเชื่อถือ และกระตุ้นให้ผู้อ่านลงมือทำตามเป้าหมายของแบรนด์", descriptionEn: "Writes distinctive content, ad copy, and articles for blogs and social media, tuning tone and wording to the audience so the brand resonates. Uses the power of words to build trust and relationships and to move readers toward the brand's goals.", skills: ["Copywriting", "SEO", "Content"] },
      { name: "YouTuber / Vlogger / TikToker", nameTh: "ผู้ผลิตเนื้อหาวิดีโอโซเชียล", description: "วางแผน ถ่ายทำ และตัดต่อคอนเทนต์วิดีโอเพื่อความบันเทิงหรือให้ความรู้บนแพลตฟอร์มวิดีโอต่าง ๆ สร้างคาแรกเตอร์ที่ชัดเจนและติดตามกระแสเพื่อสร้างฐานผู้ติดตามและการมีส่วนร่วม บทบาทนี้คืออาชีพยุคใหม่ที่เปลี่ยนความคิดสร้างสรรค์และตัวตนให้กลายเป็นทั้งอิทธิพลและรายได้", descriptionEn: "Plans, shoots, and edits video content to entertain or educate across video platforms, building a clear persona and riding trends to grow followers and engagement. A modern career that turns creativity and personality into both influence and income.", skills: ["Video Editing", "Storytelling", "Social"] },
      { name: "Social Media Specialist", nameTh: "ผู้เชี่ยวชาญการตลาดโซเชียลมีเดีย", description: "บริหารเพจ คิดแคมเปญเพื่อกระตุ้นยอดไลก์ แชร์ และการมีส่วนร่วม พร้อมวิเคราะห์กระแสและพฤติกรรมผู้คนในโลกออนไลน์ วางแผนคอนเทนต์และติดตามสถิติเพื่อปรับกลยุทธ์ให้เข้าถึงกลุ่มเป้าหมายได้มากขึ้น บทบาทนี้เชื่อมโยงความคิดสร้างสรรค์เข้ากับข้อมูลเพื่อทำให้แบรนด์เติบโตบนโซเชียลมีเดีย", descriptionEn: "Manages social pages, devises campaigns to boost likes, shares, and engagement, and reads online trends and behavior. Plans content and tracks metrics to refine strategy and reach more of the target audience, linking creativity with data to grow the brand.", skills: ["Social Media", "Analytics", "Content Plan"] },
      { name: "Social Media Administrator", nameTh: "แอดมินเพจโซเชียลมีเดีย", description: "ดูแลเพจในแต่ละวัน ทั้งการโพสต์เนื้อหา ตอบแชตพูดคุยกับลูกค้า และรักษาความเรียบร้อยของคอมมูนิตี้ เป็นด่านหน้าที่สร้างความสัมพันธ์ที่ดีระหว่างแบรนด์กับผู้ติดตามในทุกการสนทนา บทบาทนี้มีผลโดยตรงต่อภาพลักษณ์และความไว้วางใจที่ลูกค้ามีต่อแบรนด์", descriptionEn: "Runs the day-to-day of a page, posting content, replying to customer messages, and keeping the community orderly. As the front line in every conversation, this role directly shapes a brand's image and the trust customers place in it.", skills: ["Community", "Customer Care", "Scheduling"] }
    ]
  },
  {
    name: "Animation Professionals",
    nameTh: "กลุ่มที่ 3: นักสร้างสรรค์อนิเมชัน",
    careers: [
      { name: "2D/3D Modeller", nameTh: "นักปั้นโมเดล 2 มิติ / 3 มิติ", description: "ขึ้นรูปวัตถุ ตัวละคร และสิ่งของเสมือนจริงด้วยโปรแกรม 3 มิติ สำหรับงานอนิเมชัน เกม และสื่อโต้ตอบ ใส่รายละเอียดพื้นผิวและสัดส่วนให้สมจริงและพร้อมนำไปเคลื่อนไหวต่อ บทบาทนี้เป็นผู้สร้างโลกและตัวละครเสมือนที่เป็นรากฐานของผลงานภาพเคลื่อนไหวและประสบการณ์ดิจิทัลทั้งหมด", descriptionEn: "Builds objects, characters, and assets in 3D software for animation, games, and interactive media, adding texture and proportion so models look real and are ready to animate. Creates the virtual worlds and characters that underpin every animated and digital experience.", skills: ["Blender", "Maya", "3D Modeling"] },
      { name: "Character and Scene Designer", nameTh: "นักออกแบบตัวละครและฉาก", description: "ออกแบบคอนเซปต์ตัวละครและสภาพแวดล้อมให้เข้ากับเรื่องราวและอารมณ์ของงาน กำหนดสไตล์ภาพ โทนสี และบุคลิกเพื่อเป็นแนวทางให้ทีมผลิตทำงานต่อได้อย่างเป็นเอกภาพ บทบาทนี้คือผู้วางรากฐานทางสายตาและจิตวิญญาณของผลงาน ก่อนที่ทุกอย่างจะถูกสร้างให้เป็นจริง", descriptionEn: "Designs character concepts and environments that match a story's mood, defining art style, color, and personality to guide the production team toward a unified look. Lays the visual and emotional foundation of a project before anything is built.", skills: ["Concept Art", "Photoshop", "Illustration"] },
      { name: "Animator", nameTh: "นักทำอนิเมชันขยับเคลื่อนไหว", description: "ใส่คีย์เฟรมและปรับการเคลื่อนไหวของตัวละคร 2 มิติ หรือ 3 มิติ ให้ดูเป็นธรรมชาติและมีชีวิตชีวา ถ่ายทอดอารมณ์ น้ำหนัก และจังหวะผ่านการเคลื่อนที่เพื่อให้เรื่องราวน่าติดตาม บทบาทนี้คือผู้เป่าลมหายใจให้ตัวละคร เปลี่ยนภาพนิ่งให้กลายเป็นการแสดงที่สัมผัสหัวใจผู้ชมได้", descriptionEn: "Sets keyframes and refines the motion of 2D or 3D characters so they move naturally and full of life, conveying emotion, weight, and timing to make a story compelling. Breathes life into characters, turning still images into performances that move audiences.", skills: ["Animation", "Rigging", "Maya"] },
      { name: "Multimedia Artist", nameTh: "นักออกแบบศิลปะสื่อผสม", description: "ผสมผสานสื่อหลายรูปแบบ ทั้งภาพ เสียง วิดีโอ และเอฟเฟกต์ เพื่อสร้างผลงานทัศนศิลป์ที่สมบูรณ์และน่าประทับใจ ทำงานข้ามเครื่องมือและศาสตร์ต่าง ๆ เพื่อให้ได้ชิ้นงานที่เล่าเรื่องได้อย่างมีเอกลักษณ์ บทบาทนี้เหมาะกับผู้ที่ชอบทดลองและสร้างสรรค์ประสบการณ์ที่ผสานหลายประสาทสัมผัสเข้าด้วยกัน", descriptionEn: "Combines multiple media, including image, sound, video, and effects, to craft complete and striking visual works. Works across tools and disciplines to tell stories with a distinctive voice, ideal for those who love to experiment and build multi-sensory experiences.", skills: ["After Effects", "3D", "Sound"] }
    ]
  },
  {
    name: "Digital Film and Video Professionals",
    nameTh: "กลุ่มที่ 4: ภาพยนตร์และวิดีโอดิจิทัล",
    careers: [
      { name: "Screenplay Writer", nameTh: "นักเขียนบทภาพยนตร์", description: "ประพันธ์เรื่องราว โครงเรื่อง และบทสนทนาสำหรับภาพยนตร์ ละคร หรือโฆษณา วางจังหวะการเล่าเรื่องและพัฒนาตัวละครเพื่อให้เรื่องดำเนินอย่างน่าติดตามและสื่อสารแก่นเรื่องได้ชัดเจน บทบาทนี้คือจุดเริ่มต้นของทุกผลงานภาพเคลื่อนไหว เพราะบทที่ดีคือรากฐานที่ทำให้งานทั้งเรื่องมีพลัง", descriptionEn: "Writes the story, structure, and dialogue for films, dramas, or commercials, pacing the narrative and developing characters so the story stays engaging and its theme lands. The starting point of every screen project, since a strong script is the foundation that gives the whole work its power.", skills: ["Storytelling", "Screenwriting", "Structure"] },
      { name: "Director / Assistant Director", nameTh: "ผู้กำกับภาพยนตร์ / ผู้ช่วยผู้กำกับ", description: "ควบคุมทิศทางการแสดง งานภาพ และอารมณ์ของเรื่อง เพื่อแปลงบทบนกระดาษให้กลายเป็นภาพยนตร์ที่มีชีวิต ประสานงานทีมงานหน้ากองให้การถ่ายทำเดินหน้าตามวิสัยทัศน์และแผนที่วางไว้ บทบาทนี้คือผู้นำทางความคิดสร้างสรรค์ของทั้งกอง และเป็นผู้ตัดสินใจสำคัญที่กำหนดหน้าตาสุดท้ายของผลงาน", descriptionEn: "Guides the performances, visuals, and emotion of a story to turn the script into a living film, coordinating the on-set crew so shooting follows the vision and plan. Leads the creative direction of the entire production and makes the key calls that shape the final result.", skills: ["Directing", "Storyboard", "Leadership"] },
      { name: "Cameraman", nameTh: "ช่างภาพภาพยนตร์/ผู้กำกับภาพ", description: "ควบคุมการเคลื่อนกล้อง การเลือกเลนส์ และการจัดแสงหน้ากองถ่ายตามวิสัยทัศน์ของผู้กำกับ เก็บภาพแต่ละช็อตให้ได้องค์ประกอบ มุมมอง และอารมณ์ที่ตรงกับเรื่อง บทบาทนี้คือผู้วาดภาพด้วยแสงและกล้อง ซึ่งเป็นหัวใจที่ทำให้ภาพยนตร์สวยงามและสื่ออารมณ์ได้อย่างทรงพลัง", descriptionEn: "Controls camera movement, lens choice, and lighting on set to realize the director's vision, capturing each shot with the composition and mood the story calls for. Paints with light and lens, the craft at the heart of a film's beauty and emotional power.", skills: ["Cinematography", "Lighting", "Camera"] },
      { name: "Video & Audio Editor", nameTh: "นักตัดต่อภาพและเสียง", description: "นำฟุตเทจมาตัดต่อเรียงร้อย ใส่เสียงประกอบ เพลง และจังหวะให้ภาพไหลลื่นและเล่าเรื่องได้สมบูรณ์ ปรับแต่งสีและเสียงเพื่อให้ผลงานสุดท้ายสื่ออารมณ์ได้ตรงตามที่ตั้งใจ บทบาทนี้คือผู้ประกอบชิ้นส่วนทั้งหมดในห้องตัดต่อ ซึ่งเป็นขั้นตอนที่กำหนดจังหวะและความรู้สึกสุดท้ายของงาน", descriptionEn: "Cuts and arranges footage, layering sound, music, and rhythm so the visuals flow and the story feels complete, then grades color and audio to land the intended emotion. Assembles all the pieces in the edit suite, the stage that sets a work's final pace and feel.", skills: ["Premiere Pro", "DaVinci", "Sound"] },
      { name: "Special Effect Designer", nameTh: "นักออกแบบเอฟเฟกต์พิเศษ (VFX)", description: "สร้างเทคนิคภาพพิเศษ เช่น การระเบิด ควัน หรือสภาพแวดล้อม 3 มิติ ที่ไม่สามารถถ่ายทำจริงได้ ผสานภาพ CGI เข้ากับฟุตเทจจริงให้แนบเนียนและสมจริงราวกับเกิดขึ้นต่อหน้า บทบาทนี้ขยายขอบเขตของจินตนาการให้กลายเป็นภาพได้ไม่จำกัด และเป็นหัวใจของภาพยนตร์ฟอร์มใหญ่ในยุคปัจจุบัน", descriptionEn: "Creates visual effects such as explosions, smoke, or 3D environments that can't be filmed for real, blending CGI with live footage so seamlessly it looks like it happened in front of the camera. Expands imagination into limitless imagery, central to today's big-budget films.", skills: ["VFX", "Nuke", "Compositing"] }
    ]
  },
  {
    name: "Game Professionals",
    nameTh: "กลุ่มที่ 5: นักพัฒนาและสร้างสรรค์เกม",
    careers: [
      { name: "Game Assets Designer", nameTh: "นักออกแบบชิ้นงานทรัพย์สินในเกม", description: "วาดและเตรียมชิ้นงาน ไอเทม และพื้นผิว (Textures) ที่ใช้ประกอบในเกม ปรับขนาดและรายละเอียดให้เหมาะสมกับเอ็นจิ้นและทำงานได้ลื่นไหลบนอุปกรณ์ที่หลากหลาย บทบาทนี้คือผู้สร้างองค์ประกอบทางสายตาทั้งหมดที่ทำให้โลกของเกมมีชีวิตและน่าดื่มด่ำสำหรับผู้เล่น", descriptionEn: "Draws and prepares items, props, and textures used throughout a game, optimizing size and detail so they fit the engine and run smoothly across devices. Creates the visual building blocks that make a game world feel alive and immersive for players.", skills: ["2D Art", "Texturing", "Photoshop"] },
      { name: "Game Designer", nameTh: "นักออกแบบระบบการเล่นเกม", description: "ออกแบบกติกา ระดับความยาก กลไกความสนุก และโครงเรื่องของเกม ปรับสมดุลการเล่นและวางเป้าหมายให้ผู้เล่นรู้สึกท้าทายและอยากเล่นต่อ บทบาทนี้คือสถาปนิกของประสบการณ์การเล่น ที่ตัดสินว่าเกมจะสนุก ติดหนึบ และน่าจดจำเพียงใด", descriptionEn: "Designs the rules, difficulty curve, fun mechanics, and structure of a game, balancing play and setting goals so players feel challenged and want to keep going. The architect of the play experience who decides how fun, sticky, and memorable a game becomes.", skills: ["Game Design", "Level Design", "Balancing"] },
      { name: "Technician Artist", nameTh: "ศิลปินฝ่ายเทคนิคเกม", description: "เป็นตัวกลางระหว่างทีมโปรแกรมเมอร์และทีมอาร์ตเพื่อนำชิ้นงานกราฟิกเข้าสู่เอ็นจิ้นเกมอย่างราบรื่น ปรับแต่งให้ภาพสวยงามและประสิทธิภาพดีโดยไม่กระทบความลื่นไหลของเกม บทบาทนี้ต้องเข้าใจทั้งศิลปะและเทคนิค จึงเป็นกุญแจสำคัญที่ทำให้วิสัยทัศน์ด้านภาพกลายเป็นเกมที่เล่นได้จริง", descriptionEn: "Bridges the programming and art teams to bring graphics into the game engine smoothly, tuning visuals for both beauty and performance without hurting the game's frame rate. Understanding both art and tech, this role is key to turning a visual vision into a playable game.", skills: ["Unity", "Shaders", "Pipeline"] }
    ]
  },
  {
    name: "Digital Media Planning Professionals (Production)",
    nameTh: "กลุ่มที่ 6: การวางแผนและการผลิตสื่อดิจิทัล",
    careers: [
      { name: "Producer", nameTh: "ผู้อำนวยการสร้าง", description: "จัดสรรงบประมาณ วางไทม์ไลน์ และดูแลควบคุมงานผลิตทั้งหมดให้เสร็จตามแผนและคุณภาพที่ตั้งไว้ ประสานทุกฝ่ายตั้งแต่ทีมสร้างสรรค์ไปจนถึงลูกค้าเพื่อให้โปรเจกต์เดินหน้าได้อย่างราบรื่น บทบาทนี้คือผู้ที่ทำให้ไอเดียเกิดขึ้นจริงได้ภายใต้ทรัพยากรและเวลาที่มีจำกัด", descriptionEn: "Allocates budget, sets timelines, and oversees the entire production to finish on plan and on quality, coordinating everyone from the creative team to the client so the project moves smoothly. The person who makes ideas happen within limited time and resources.", skills: ["Project Mgmt", "Budgeting", "Production"] },
      { name: "Creative", nameTh: "นักคิดสร้างสรรค์เนื้อหาสื่อ", description: "ระดมสมองคิดคอนเซปต์และไอเดียใหม่ ๆ สำหรับรายการ แคมเปญ หรืองานโฆษณา วางแนวทางการนำเสนอที่แปลกใหม่และตรงกับกลุ่มเป้าหมายเพื่อให้งานโดดเด่นและน่าจดจำ บทบาทนี้คือต้นน้ำของความคิดสร้างสรรค์ ที่เปลี่ยนโจทย์ทางการตลาดให้กลายเป็นเรื่องราวที่ผู้คนอยากพูดถึง", descriptionEn: "Brainstorms fresh concepts and ideas for shows, campaigns, or ads, shaping novel, audience-fit presentations so the work stands out and sticks. The source of creative thinking that turns a marketing brief into a story people want to talk about.", skills: ["Ideation", "Concept", "Storytelling"] },
      { name: "Account Executive", nameTh: "ผู้บริหารฝ่ายบริการลูกค้า (AE)", description: "ประสานงานระหว่างลูกค้าที่ว่าจ้างและทีมผลิตภายในบริษัทเพื่อให้งานออกมาตรงกับบรีฟและความคาดหวัง ดูแลไทม์ไลน์ งบประมาณ และรายละเอียดต่าง ๆ เพื่อให้ทั้งสองฝ่ายพึงพอใจในผลงาน บทบาทนี้คือผู้รักษาความสัมพันธ์และความไว้วางใจ ซึ่งเป็นหัวใจของธุรกิจบริการและเอเจนซี", descriptionEn: "Coordinates between the paying client and the internal production team so the work matches the brief and expectations, managing timeline, budget, and details to satisfy both sides. The keeper of relationships and trust, which is the heart of agency and service businesses.", skills: ["Client Service", "Communication", "Planning"] }
    ]
  },
  {
    name: "Marketing & Communication Professionals",
    nameTh: "กลุ่มที่ 7: การตลาดและการสื่อสารประชาสัมพันธ์",
    careers: [
      { name: "Public Relations Officer", nameTh: "เจ้าหน้าที่ประชาสัมพันธ์ (PR)", description: "เขียนข่าวประชาสัมพันธ์ วางแผนการสื่อสาร และสร้างภาพลักษณ์ที่ดีให้กับองค์กรหรือแบรนด์ ดูแลความสัมพันธ์กับสื่อมวลชนและรับมือกับประเด็นต่าง ๆ อย่างเหมาะสมและทันท่วงที บทบาทนี้คือผู้ปกป้องและเสริมสร้างชื่อเสียงขององค์กร ซึ่งเป็นสินทรัพย์ที่มีค่าและสร้างยากที่สุดอย่างหนึ่ง", descriptionEn: "Writes press releases, plans communications, and builds a positive image for an organization or brand, nurturing media relationships and handling issues appropriately and in time. Protects and strengthens reputation, one of the most valuable and hardest-won assets an organization has.", skills: ["PR", "Press Release", "Communication"] },
      { name: "Marketing Coordinator / Digital Marketing", nameTh: "ผู้ประสานงานและนักการตลาดดิจิทัล", description: "วางแผนโฆษณา ยิงแอด วิเคราะห์กลุ่มเป้าหมาย และติดตามผลการขายผ่านช่องทางออนไลน์ ปรับแคมเปญจากข้อมูลจริงเพื่อให้คุ้มค่างบประมาณและได้ผลลัพธ์ตามเป้าหมาย บทบาทนี้ผสานความคิดสร้างสรรค์เข้ากับการวัดผลที่จับต้องได้ จึงเป็นกำลังสำคัญที่ขับเคลื่อนยอดขายและการเติบโตของธุรกิจ", descriptionEn: "Plans advertising, runs ad campaigns, analyzes target audiences, and tracks online sales, optimizing from real data to spend efficiently and hit goals. Blends creativity with measurable results, a key force driving sales and business growth.", skills: ["Google Ads", "Meta Ads", "Analytics"] },
      { name: "Social Media Expert / Social Media Strategist", nameTh: "นักวางกลยุทธ์สื่อโซเชียล", description: "กำหนดทิศทางและกลยุทธ์ระยะยาวในการสร้างแบรนด์ผ่านแพลตฟอร์มอย่าง TikTok, Instagram และ Facebook วางแผนภาพรวมของคอนเทนต์และวัดผลเพื่อให้แบรนด์เติบโตอย่างมีทิศทางและยั่งยืน บทบาทนี้มองเกมระยะยาวมากกว่าการทำคอนเทนต์รายวัน และเป็นผู้กำหนดว่าแบรนด์จะยืนอยู่ตรงไหนในใจผู้คน", descriptionEn: "Sets the long-term direction and strategy for building a brand across platforms like TikTok, Instagram, and Facebook, planning the overall content picture and measuring results for steady, sustainable growth. Plays the long game beyond daily posting, defining where a brand stands in people's minds.", skills: ["Strategy", "Content Plan", "Analytics"] }
    ]
  },
  {
    name: "Real-time Reporting Professionals (New Media)",
    nameTh: "กลุ่มที่ 8: วารสารศาสตร์ยุคใหม่และการรายงานสด",
    careers: [
      { name: "Data Journalist", nameTh: "นักข่าวข้อมูล", description: "สืบค้นประเด็นข่าวจากชุดข้อมูลดิบและสถิติ แล้วนำเสนอผ่านอินโฟกราฟิกและภาพที่เข้าใจง่าย เปลี่ยนตัวเลขที่ซับซ้อนให้กลายเป็นเรื่องราวที่ผู้อ่านเห็นภาพและเชื่อถือได้ บทบาทนี้ผสานทักษะการเป็นนักข่าวเข้ากับการวิเคราะห์ข้อมูล จึงสำคัญอย่างยิ่งในยุคที่ข้อมูลล้นและข่าวลวงแพร่กระจายง่าย", descriptionEn: "Investigates stories from raw data and statistics, presenting findings through clear infographics and visuals that turn complex numbers into trustworthy, vivid stories. Combines journalism with data analysis, vital in an age of information overload and easy-spreading misinformation.", skills: ["Data Viz", "Research", "Storytelling"] },
      { name: "Online News Reporter", nameTh: "ผู้รายงานข่าวด่วนออนไลน์", description: "เขียนสรุปประเด็นข่าวร้อน เกาะติดกระแสสังคม และนำเสนอผ่านแพลตฟอร์มข่าวดิจิทัลอย่างรวดเร็ว ตรวจสอบข้อเท็จจริงอย่างรอบคอบเพื่อให้ข่าวถูกต้องและทันเหตุการณ์ บทบาทนี้ทำงานแข่งกับเวลาเพื่อส่งข้อมูลที่เชื่อถือได้ถึงผู้อ่านก่อนใคร ในยุคที่ข่าวสารเปลี่ยนแปลงทุกวินาที", descriptionEn: "Summarizes breaking stories, follows social trends, and publishes fast on digital news platforms while fact-checking carefully to stay accurate and timely. Races the clock to get reliable information to readers first, in an era where news changes by the second.", skills: ["News Writing", "Fact-checking", "CMS"] },
      { name: "One-Man-Band Journalist", nameTh: "นักข่าวมัลติมีเดียครบวงจร", description: "ทำงานข่าวคนเดียวครบทุกบทบาท ทั้งสืบค้นข้อมูล ถ่ายภาพ เขียนบท ตัดต่อ และรายงานสด เหมาะกับยุคที่ต้องผลิตคอนเทนต์ข่าวได้เร็วและครบวงจรในตัวคนเดียว บทบาทนี้ต้องการคนที่มีทักษะหลากหลายและปรับตัวสูง จึงเป็นภาพสะท้อนของวงการสื่อยุคใหม่ที่ยืดหยุ่นและคล่องตัว", descriptionEn: "Handles every newsroom role alone, researching, shooting, scripting, editing, and reporting live, suited to an era that demands fast, end-to-end news content from a single person. Calls for versatile, highly adaptable skills, a mirror of today's lean, agile media industry.", skills: ["Reporting", "Video", "Editing"] }
    ]
  },
  {
    name: "Application Professionals",
    nameTh: "กลุ่มที่ 9: พัฒนาแอปพลิเคชันสื่อและข้อมูล",
    careers: [
      { name: "UX/UI Designer (Mobile)", nameTh: "นักออกแบบ UI/UX แอปพลิเคชันมือถือ", description: "ออกแบบโครงร่างและส่วนติดต่อผู้ใช้ที่เหมาะกับการปัดและแตะบนหน้าจอมือถือโดยเฉพาะ คำนึงถึงขนาดนิ้ว พื้นที่จำกัด และบริบทการใช้งานระหว่างเดินทาง เพื่อให้แอปใช้งานง่ายและสบายตา บทบาทนี้สำคัญต่อความสำเร็จของแอป เพราะประสบการณ์ที่ดีบนมือถือคือสิ่งที่ทำให้ผู้ใช้กลับมาใช้ซ้ำ", descriptionEn: "Designs layouts and interfaces tailored to swipe-and-tap use on mobile screens, accounting for finger size, limited space, and on-the-go context so apps stay easy and comfortable to use. Key to an app's success, since great mobile experience is what keeps users coming back.", skills: ["Figma", "Mobile UX", "Prototyping"] },
      { name: "Cross-platform Mobile Developer", nameTh: "นักพัฒนาแอปมือถือหลายระบบ", description: "พัฒนาแอปนำเสนอสื่อมัลติมีเดียที่ทำงานลื่นไหลทั้งบน Android และ iOS จากโค้ดชุดเดียว เน้นการเล่นภาพและเสียงที่ราบรื่นและประสบการณ์ใช้งานที่ดีบนทุกอุปกรณ์ บทบาทนี้ช่วยให้ทีมส่งมอบแอปคุณภาพถึงผู้ใช้ทั้งสองระบบได้รวดเร็วและคุ้มค่าต้นทุนการพัฒนา", descriptionEn: "Develops media-rich apps that run smoothly on both Android and iOS from a single codebase, focusing on seamless playback and a strong experience on every device. Lets teams deliver quality apps to both platforms quickly and cost-effectively.", skills: ["Flutter", "React Native", "Media"] }
    ]
  },
  {
    name: "Personalized / Research Professionals",
    nameTh: "กลุ่มที่ 10: งานวิจัย ประเมินผล และผู้ประกอบการสื่อ",
    careers: [
      { name: "Digital Media Evaluator and Testing", nameTh: "นักประเมินและทดสอบสื่อดิจิทัล", description: "ตรวจสอบและประเมินคุณภาพของคอนเทนต์ ความสอดคล้องทางกฎหมาย และจริยธรรมของสื่อ ทดสอบการใช้งานจริงและให้ข้อเสนอแนะเพื่อปรับปรุงก่อนเผยแพร่สู่สาธารณะ บทบาทนี้เป็นผู้ควบคุมคุณภาพและความน่าเชื่อถือของสื่อ ซึ่งสำคัญมากในยุคที่เนื้อหาส่งผลต่อความคิดและความรู้สึกของผู้คนจำนวนมาก", descriptionEn: "Audits and evaluates content quality, legal compliance, and media ethics, running real-world tests and giving feedback for improvement before public release. Guards the quality and credibility of media, vital in an age where content shapes how large audiences think and feel.", skills: ["QA", "Compliance", "Testing"] },
      { name: "Digital Entrepreneur", nameTh: "ผู้ประกอบการธุรกิจสื่อดิจิทัล", description: "เปิดธุรกิจ สตูดิโอ หรือเอเจนซีผลิตงานศิลปะและคอนเทนต์ความบันเทิงของตนเอง ดูแลตั้งแต่งานสร้างสรรค์ไปจนถึงการบริหารทีม การเงิน และการหาลูกค้าเพื่อให้ธุรกิจอยู่รอดและเติบโต บทบาทนี้เหมาะกับผู้ที่มีทั้งหัวใจศิลปินและหัวคิดทางธุรกิจ และต้องการเป็นเจ้าของผลงานและทิศทางของตนเอง", descriptionEn: "Launches their own studio or agency producing art and entertainment content, overseeing everything from creative work to team management, finance, and client acquisition. Suited to those with both an artist's heart and a business mind who want to own their work and direction.", skills: ["Entrepreneurship", "Production", "Business"] },
      { name: "Personalized Career", nameTh: "อาชีพสื่อประยุกต์เฉพาะทาง", description: "อาชีพสื่อที่ออกแบบขึ้นเองโดยผสมผสานศาสตร์การสื่อสาร มัลติมีเดีย และทักษะเฉพาะด้านที่สนใจเข้าด้วยกัน เหมาะกับผู้ที่อยากสร้างบทบาทใหม่ในวงการสื่อซึ่งยังไม่มีนิยามตายตัว บทบาทนี้เปิดโอกาสให้คุณผสมจุดแข็งและความหลงใหลของตัวเองเป็นเส้นทางอาชีพที่ไม่เหมือนใคร", descriptionEn: "A self-designed media career that blends communication, multimedia, and specialized skills you're passionate about, suited to those who want to create a new, not-yet-defined role in media. Lets you combine your strengths and passions into a one-of-a-kind path.", skills: ["Multimedia", "Adaptability", "Creativity"] }
    ]
  }
];

export function getGroupSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}
